title: Grassroots Science
description: A global initiative focused on developing state-of-the-art multilingual language models through grassroots efforts.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
