title: Grassroots Science
description: A global initiative focused on developing state-of-the-art multilingual language models through grassroots efforts.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
hf_link: https://huggingface.com/grassroots-science
x_link: https://x.com/GrassrootsSci
github_link: https://github.com/grassroots-science
